export const SURVEY_LIST_REQUEST = "SURVEY_LIST_REQUEST";
export const SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS";
export const SURVEY_LIST_FAIL = "SURVEY_LIST_FAIL";

export const SURVEY_ADD_REQUEST = "SURVEY_ADD_REQUEST";
export const SURVEY_ADD_SUCCESS = "SURVEY_ADD_SUCCESS";
export const SURVEY_ADD_FAIL = "SURVEY_ADD_FAIL";
